# Create data
Create a standard data frame from scratch

```{r}
id <- c(1:10)

name <- c("John Mendes", "Rob Stewart", "Rachel Abrahamson", "Christy Hickman", "Johnson Harper", "Candace Miller", "Carlson Landy", "Pansy Jordan", "Darius Berry", "Claudia Garcia")

job_title <- c("Professional", "Programmer", "Management", "Clerical", "Developer", "Programmer", "Management", "Clerical", "Developer", "Programmer")

employee <- data.frame(id, name, job_title)

print(employee)
```
Separate name to first name and last name

```{r}
employee <- separate(employee, name, into = c("first_name", "last_name"), sep = ' ')
print(employee)
```

Still want to keep the full name?

```{r}
employee <- employee %>% 
  mutate(full_name = unite(employee, 'full_name', first_name, last_name, sep = ' ')$full_name, .before = first_name)
print(employee)
```

# Transform between long and wide format
### Wide data
```{r}
library(tidyr)
employee %>% 
  pivot_wider(names_from = job_title, values_from = full_name)
```
### Long data
https://tidyr.tidyverse.org/articles/pivot.html 


